server: 
  port: 8701   # 定义服务端口 

eureka: 
  instance:
    instance-id: config-8701.com
  client:
    serviceUrl: 
      defaultZone: 
        http://edmin:mldnjava@eureka-7001.com:7001/eureka/

spring: 
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mldn/microconfig.git
  application:
    name: micro-cloud-config