server: 
  port: 8701   # 定义服务端口 
eureka:
  instance:
    instance-id: gateway-8501.com
  client:
    serviceUrl: 
      defaultZone: 
        http://edmin:mldnjava@eureka-7001.com:7001/eureka/
spring:
  application:
    name: micro-cloud-oauth2