server: 
  port: 7001   # 定义服务端口 
eureka:
  instance:
    hostname: eureka-7001.com  # 运行的主机名称
  client:
    registerWithEureka: false # 不向eureka中注册
    fetchRegistry: false # 不通过eureka抓取配置
    serviceUrl: # 定义所有注册的eureka的地址
      defaultZone: http://eureka-7001.com:7001/eureka/
