server: 
  port: 80   # 定义服务端口
eureka:
  client:
    register-with-eureka: false  # 客户端不需要进行Eureka服务注册
    serviceUrl: 
      defaultZone: 
        http://edmin:mldnjava@eureka-7001.com:7001/eureka/
